#!/usr/bin/env bash
set -e

if [ ! -e root.x86_64 ]; then
    mkdir root.x86_64
    curl https://repo.voidlinux.eu/live/current/void-x86_64-musl-ROOTFS-20171007.tar.xz | tar xJp -C root.x86_64
fi

docker build -t godarch/void .
docker push godarch/void
