#!/usr/bin/env bash
set -e

if [ ! -e root.x86_64 ]; then
    mkdir root.x86_64
    debootstrap --include=linux-image-generic cosmic root.x86_64 http://archive.ubuntu.com/ubuntu/
fi

if [ ! -e root.x86_64.tar.gz ]; then
    cd root.x86_64
    tar -czpf ../root.x86_64.tar.gz *
    cd ..
fi

docker build --squash -t godarch/ubuntu:cosmic .
docker tag godarch/ubuntu:cosmic godarch/ubuntu:cosmic-$TAG
docker tag godarch/ubuntu:cosmic godarch/ubuntu:latest
