#!/usr/bin/env bash
set -e

TAG="$1"

docker push godarch/debian:latest
docker push godarch/debian:testing
docker push godarch/debian:testing-$TAG

docker push godarch/debian:stretch
docker push godarch/debian:stretch-$TAG