#!/usr/bin/env bash
set -e

if [ ! -e root.x86_64 ]; then
    mkdir root.x86_64
    debootstrap --include=linux-image-generic,grub-efi $1 root.x86_64 http://archive.ubuntu.com/ubuntu/
fi

if [ ! -e root.x86_64.tar.gz ]; then
    pushd root.x86_64
    tar -czpf ../root.x86_64.tar.gz *
    popd 
fi

docker build --squash -t godarch/ubuntu:$1 .
docker tag godarch/ubuntu:disco godarch/ubuntu:$1-$TAG
